@startuml
title G&G Revamp

skinparam shadowing false
skinparam linetype ortho
skinparam defaultTextAlignment center

' ---------- ZONE STYLE ----------
skinparam package {
  BorderStyle dashed
  BorderThickness 1
}

skinparam rectangle {
  RoundCorner 18
  BorderThickness 1
}

' ---------- ACTORS / DEVICES ----------
actor Staff
'--------POS DEVICES ---------------
package "POS Device " {
rectangle "YPS POS" as POS
rectangle "Sunmi POS" as SPOS
}
' ---------- EXTERNAL SERVICES ----------
package "External Services" {
  rectangle "YPS Service"
  package "Mobile Service"{
  rectangle "MPT"
  rectangle "ATOM"
  }
}

' ---------- FRONTEND ----------
package "G&G FrontEnd" {

  rectangle "Eservice"
}

' ---------- AWS HOSTED ----------
package "Alibaba Cloud" {

  package "G&G Middleware" {
    rectangle "G&G Backend"
    queue "RabbitMQ"
  }

  rectangle "Sale Service"

}
' ---------- DB  ----------
package "Database " {
 database "Integration DB"
 database "YPS Integration DB"
 database "Sale DB"
 database "Sale Old DB"
 database "QueueProcess DB"
}


' ---------- ERP ----------
rectangle "Microsoft AX"

' ---------- FLOWS ----------
Staff --> "G&G FrontEnd":HTTPS
Staff --> "POS Device "
"G&G FrontEnd" --> "G&G Middleware" : HTTPS
"G&G FrontEnd" --> "Mobile Service": HTTPS
"G&G Backend" --> "Integration DB": JDBC(connection)
"G&G Backend" --> "QueueProcess DB": (mq_status,retry_count)
"G&G Backend" --> "YPS Integration DB": YPS data store seperate
"G&G Backend" --> RabbitMQ : AMQP (publish)
"Sale DB" --> "Sale Old DB": Archive data per year
RabbitMQ --> "Sale Service" : AMQP (consume)
RabbitMQ --> "QueueProcess DB" : update processing status

"Sale Service" --> "Sale DB" : JDBC
"Sale Service" --> "Microsoft AX" : Integration

"POS Device " --> "YPS Service"
"YPS Service" --> "G&G Middleware" : Callback

@enduml
